fantasy_sports_admin:
    resource: "@FantasySportsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fantasy_sports_site:
    resource: "@FantasySportsSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
