# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    mongo_client:
        class: MongoClient
        arguments: ['mongodb://%mongodb_host%:27017']

    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: FantasySports\AdminBundle\Form\InvitationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: FantasySports\AdminBundle\Form\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: FantasySports\AdminBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false