# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    mongo_client:
        class: MongoClient
        arguments: ['mongodb://%mongodb_host%:27017']

    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    account.register_listener:
        class: FantasySports\AdminBundle\Listener\FosUserListener
        arguments: ['@doctrine.orm.entity_manager', '@service_container']
        tags:
            - { name: 'kernel.event_subscriber' }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]