fantasy_sports_admin_dashboard:
    path:     /
    defaults: { _controller: FantasySportsAdminBundle:Index:dashboard }

fantasy_sports_admin_pass_save:
    path:     /pass/save
    defaults: { _controller: FantasySportsAdminBundle:Pass:save }

fantasy_sports_admin_pass_add:
    path:     /pass
    defaults: { _controller: FantasySportsAdminBundle:Pass:add }

fantasy_sports_admin_pass_list:
    path:     /passes
    defaults: { _controller: FantasySportsAdminBundle:Pass:list, status: -1 }

fantasy_sports_admin_pass_detail:
    path:     /pass/{passId}/detail
    defaults: { _controller: FantasySportsAdminBundle:Pass:detail, passId: 0 }

fantasy_sports_admin_pass_register:
    path:     /pass/register/v1/devices/{deviceId}/registrations/{passId}/{serialNumber}
    defaults: { _controller: FantasySportsAdminBundle:Pass:register }
    methods:  [POST]

fantasy_sports_admin_pass_deregister:
    path:     /pass/register/v1/devices/{deviceId}/registrations/{passId}/{serialNumber}
    defaults: { _controller: FantasySportsAdminBundle:Pass:deregister }
    methods:  [DELETE]

fantasy_sports_admin_pass_active:
    path:     /passes/active
    defaults: { _controller: FantasySportsAdminBundle:Pass:list, status: 0 }

fantasy_sports_admin_pass_won:
    path:     /passes/won
    defaults: { _controller: FantasySportsAdminBundle:Pass:list, status: 1 }

fantasy_sports_admin_pass_lost:
    path:     /passes/lost
    defaults: { _controller: FantasySportsAdminBundle:Pass:list, status: 2 }

fantasy_sports_admin_transaction_list:
    path:     /transactions
    defaults: { _controller: FantasySportsAdminBundle:Transaction:list, user: -1 }

fantasy_sports_admin_user_list:
    path:     /users
    defaults: { _controller: FantasySportsAdminBundle:User:list }

fantasy_sports_admin_news_list:
    path:     /news
    defaults: { _controller: FantasySportsAdminBundle:News:list }

fantasy_sports_admin_event_list:
    path:     /events
    defaults: { _controller: FantasySportsAdminBundle:Event:list }

fantasy_sports_admin_coupon:
    path:     /coupon
    defaults: { _controller: FantasySportsAdminBundle:Coupon:coupon }

fantasy_sports_admin_coupon_list:
    path:     /coupons
    defaults: { _controller: FantasySportsAdminBundle:Coupon:list }

fantasy_sports_admin_coupon_add:
    path:     /coupon/add
    defaults: { _controller: FantasySportsAdminBundle:Coupon:add }

fantasy_sports_admin_rules:
    path:     /rules
    defaults: { _controller: FantasySportsAdminBundle:Rules:index }

fantasy_sports_ranking_week:
    path:     /ranking/week
    defaults: { _controller: FantasySportsAdminBundle:Ranking:rankingWeek }

fantasy_sports_ranking_general:
    path:     /ranking/general
    defaults: { _controller: FantasySportsAdminBundle:Ranking:rankingGeneral }

fantasy_sports_ticket_new:
    path:     /ticket
    defaults: { _controller: FantasySportsAdminBundle:Ticket:new }

fantasy_sports_ticket_list:
    path:     /tickets
    defaults: { _controller: FantasySportsAdminBundle:Ticket:list }

fantasy_sports_ticket_save:
    path:     /ticket/save
    defaults: { _controller: FantasySportsAdminBundle:Ticket:save }

fantasy_sports_ticket_view:
    path:     /ticket/{ticketId}
    defaults: { _controller: FantasySportsAdminBundle:Ticket:view }

fantasy_sports_ticket_answer_save:
    path:     /ticket/{ticketId}/answer/save
    defaults: { _controller: FantasySportsAdminBundle:Ticket:answerSave }

fantasy_sports_service_califica:
    path:     /califica
    defaults: { _controller: FantasySportsAdminBundle:Service:califica }

fantasy_sports_service_ordena:
    path:     /ordena
    defaults: { _controller: FantasySportsAdminBundle:Service:ordena }

fantasy_sports_service_notifica:
    path:     /notifica
    defaults: { _controller: FantasySportsAdminBundle:Service:notifica }