fantasy_sports_admin_dashboard:
    path:     /
    defaults: { _controller: FantasySportsAdminBundle:Index:dashboard }

fantasy_sports_admin_pass_save:
    path:     /pass/save
    defaults: { _controller: FantasySportsAdminBundle:Pass:save }

fantasy_sports_admin_pass_add:
    path:     /pass
    defaults: { _controller: FantasySportsAdminBundle:Pass:add }

fantasy_sports_admin_pass_list:
    path:     /passes
    defaults: { _controller: FantasySportsAdminBundle:Pass:list }