<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * CartaProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartaProductRepository extends \Doctrine\ORM\EntityRepository
{
}
