<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * CartaCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartaCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
