<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * InvitationSentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationSentRepository extends \Doctrine\ORM\EntityRepository
{
}
