<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaseDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
