<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * PaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaseRepository extends \Doctrine\ORM\EntityRepository
{
}
