<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * PaseDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaseDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
