<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * SportMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
