<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * TicketAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
