<?php

namespace FantasySports\AdminBundle\Repository;

/**
 * WalletTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
